apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: desafio-kubernets
  labels:
    app.kubernetes.io/part-of: desafio-kubernets
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres-bd
    app.kubernetes.io/managed-by: kubectl
data:
  POSTGRES_DB: postdb
  init.sql: |
    CREATE TABLE IF NOT EXISTS tarefas (
        id SERIAL PRIMARY KEY,
        titulo VARCHAR(255) NOT NULL,
        concluida BOOLEAN DEFAULT FALSE
    );

    -- Role para acesso anônimo da API (sem senha)
    CREATE ROLE web_anon NOLOGIN;
    GRANT USAGE ON SCHEMA public TO web_anon;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO web_anon;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO web_anon;