apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: desafio-kubernets
  labels:
    app.kubernetes.io/part-of: desafio-kubernets
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres-bd
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres