apiVersion: v1
kind: Service
metadata:
  name: postgrest-service
  namespace: desafio-kubernetes
  labels:
    app.kubernetes.io/part-of: desafio-kubernetes
    app.kubernetes.io/name: postgrest
    app.kubernetes.io/instance: postgrest-api
    app.kubernetes.io/managed-by: kubectl
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: postgrest